import { asciiLower } from '../../parsers/csv/index.js';
import { parseYaml, type YamlNode, type YamlParserDeps } from '../../parsers/yaml/index.js';
import type { Diagnostic } from '../../parsers/types.js';
export type YamlAction = { type: 'set-mode'; mode: 'tree' | 'flat' | 'json' | 'raw' } | { type: 'select-document'; index: number } | { type: 'toggle-node'; id: string } | { type: 'expand-all' } | { type: 'collapse-all' } | { type: 'set-search'; search: string } | { type: 'edit-source'; text: string };
export interface YamlViewState { status: 'ok' | 'partial' | 'failed'; documents: readonly YamlNode[]; selectedDocument: number; mode: 'tree' | 'flat' | 'json' | 'raw'; search: string; expanded: ReadonlySet<string>; diagnostics: readonly Diagnostic[]; text: string; }
export interface YamlController { readonly state: YamlViewState; dispatch(action: YamlAction): void; subscribe(listener: (state: YamlViewState) => void): () => void; nodePath(id: string): string; nodeValue(id: string): string; nodeJson(id: string): string; documentJson(): string; }
export function createYamlController(input: Uint8Array | string, deps?: YamlParserDeps): YamlController {
    const listeners = new Set<(state: YamlViewState) => void>(), nodes = new Map<string, YamlNode>();
    const state: YamlViewState = { status: 'ok', documents: [], selectedDocument: 0, mode: 'tree', search: '', expanded: new Set(), diagnostics: [], text: typeof input === 'string' ? input : new TextDecoder().decode(input) };
    const index = (): void => { const result = parseYaml(state.text, deps ? { deps } : {}).result; state.status = result.status; state.diagnostics = result.diagnostics; state.documents = result.status === 'failed' ? [] : result.document.documents; state.selectedDocument = Math.min(state.selectedDocument, Math.max(0, state.documents.length - 1)); nodes.clear(); const walk = (node: YamlNode): void => { nodes.set(node.path, node); for (const child of node.children ?? []) walk(child); }; state.documents.forEach(walk); };
    const plain = (node: YamlNode): unknown => node.children ? node.kind === 'seq' ? node.children.map(plain) : Object.fromEntries(node.children.map(child => [child.key, plain(child)])) : node.value;
    const notify = (): void => listeners.forEach(listener => listener(state)); index(); state.expanded = new Set(state.documents.flatMap(node => [node.path, ...(node.children ?? []).filter(child => !!child.children?.length).map(child => child.path)]));
    return { state, subscribe(listener) { listeners.add(listener); return () => listeners.delete(listener); }, nodePath: id => nodes.get(id)?.path ?? '', nodeValue: id => nodes.get(id)?.raw ?? String(nodes.get(id)?.value ?? ''), nodeJson: id => JSON.stringify(plain(nodes.get(id) ?? state.documents[state.selectedDocument]!), null, 2), documentJson() { const document = state.documents[state.selectedDocument]; return document ? JSON.stringify(plain(document), null, 2) : ''; }, dispatch(action) { if (action.type === 'edit-source') { state.text = action.text; index(); } else if (action.type === 'set-mode') state.mode = action.mode; else if (action.type === 'select-document') state.selectedDocument = Math.max(0, Math.min(action.index, state.documents.length - 1)); else if (action.type === 'set-search') { state.search = action.search; const query = asciiLower(action.search); if (query) nodes.forEach(node => { if (asciiLower(`${node.key} ${node.path} ${node.raw ?? node.value ?? ''}`).includes(query)) { let current: YamlNode | undefined = node; while (current) { state.expanded = new Set([...state.expanded, current.path]); current = [...nodes.values()].find(candidate => candidate.children?.includes(current!)); } } }); } else if (action.type === 'toggle-node') { const expanded = new Set(state.expanded); expanded.has(action.id) ? expanded.delete(action.id) : expanded.add(action.id); state.expanded = expanded; } else if (action.type === 'expand-all') state.expanded = new Set(nodes.keys()); else state.expanded = new Set(); notify(); } };
}
