import { markdownViewerCss } from '../markdown/styles.js';

// Reuse Markdown prose, tables, math, and highlighter styles unchanged.
export const notebookViewerCss = markdownViewerCss + `
.omni-viewer--notebook.omni-notebook{box-sizing:border-box;display:flex;flex-direction:column;gap:14px;height:100%;min-height:360px;padding:18px;color:var(--omni-fg,#d4d4d4);background:var(--omni-bg,#1e1e1e);font:var(--omni-font-size,13px)/1.5 var(--omni-font-family,system-ui,sans-serif);--md-border:var(--omni-border,#454545);--md-muted:var(--omni-muted,#aaa);--md-panel:var(--omni-panel-bg,rgba(127,127,127,.05));--md-code:var(--omni-code-bg,rgba(127,127,127,.14))}
.omni-notebook *{box-sizing:border-box}.omni-notebook [hidden]{display:none!important}
.omni-notebook__header,.omni-notebook__toolbar,.omni-notebook__cell-header{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.omni-notebook__header{justify-content:space-between}.omni-notebook__title{font-size:17px;margin:0;overflow-wrap:anywhere}.omni-notebook__summary,.omni-notebook__note{color:var(--md-muted);font-size:12px}.omni-notebook__toolbar label{display:flex;gap:6px;align-items:center}.omni-notebook__toolbar input[type=search]{flex:1;min-width:160px;padding:7px 10px;border:1px solid var(--md-border);border-radius:6px;color:inherit;background:var(--md-panel);font:inherit}.omni-notebook__toolbar input:focus-visible,.omni-notebook summary:focus-visible{outline:2px solid var(--omni-focus,#007fd4);outline-offset:2px}
.omni-notebook__cells{flex:1;min-height:0;overflow:auto;display:flex;flex-direction:column;gap:14px}.omni-notebook__cell{border:1px solid var(--md-border);border-radius:8px;background:var(--md-panel);flex:none;overflow:hidden}.omni-notebook__cell-header{padding:8px 14px;border-bottom:1px solid var(--md-border);color:var(--md-muted);font-size:12px}.omni-notebook__cell-header.is-error,.omni-notebook__error{color:var(--omni-error,#f44747);background:rgba(244,71,71,.09)}.omni-notebook__cell-header .omni-notebook__prompt{margin-left:auto;font-family:var(--omni-mono,monospace)}
.omni-notebook summary{cursor:pointer;padding:8px 14px;color:var(--md-muted)}.omni-notebook__source pre,.omni-notebook__raw,.omni-notebook__text{margin:0;padding:14px;white-space:pre-wrap;overflow-wrap:anywhere;overflow:auto;font:13px/1.55 var(--omni-mono,monospace);tab-size:4}.omni-notebook__source pre{background:var(--md-code)}.omni-notebook__outputs{border-top:1px solid var(--md-border)}.omni-notebook__output+.omni-notebook__output{border-top:1px solid var(--md-border)}.omni-notebook__output-label{padding:6px 14px 0;color:var(--md-muted);font:12px/1.5 var(--omni-mono,monospace)}.omni-notebook .omni-markdown__preview{padding:18px;overflow:auto}.omni-notebook__image{display:block;max-width:100%;height:auto;margin:14px}.omni-notebook__stderr{color:var(--omni-warning,#cca700)}.omni-notebook__warning{margin:0;padding:10px 14px;border-left:3px solid var(--omni-warning,#cca700);white-space:pre-wrap}.omni-notebook__empty{padding:24px;text-align:center;color:var(--md-muted)}
`;
