import type { HostContext } from '../host/index.js'; import { MountAbortedError, VIEWER_ROOT_CLASS, type MountOptions, type ViewerHandle, type ViewerInput } from './types.js';
export const diagramViewerCss=`.omni-diagram{box-sizing:border-box;min-height:100%;padding:18px;background:var(--omni-bg,#1e1e1e);color:var(--omni-fg,#ddd);font:14px/1.45 system-ui,sans-serif}.omni-diagram *{box-sizing:border-box}.omni-diagram__header{display:flex;justify-content:space-between;gap:16px;margin-bottom:12px}.omni-diagram__title{font-size:18px;font-weight:650;overflow-wrap:anywhere}.omni-diagram__stage{overflow:auto;min-height:300px;padding:18px;border:1px solid var(--omni-border,#444);border-radius:8px;background:#fff;color:#111}.omni-diagram__stage svg{display:block;max-width:100%;height:auto;margin:auto}.omni-diagram__warning{margin-top:12px;padding:10px;border:1px solid #b98b2f;border-radius:6px;background:#3b2d10;color:#ffd98a;white-space:pre-wrap}.omni-diagram__source-details{margin-top:12px}.omni-diagram__source-details summary{cursor:pointer}.omni-diagram__source{max-height:240px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}`;
export interface DiagramMountOptions extends MountOptions { renderMermaid?(id:string,source:string):Promise<string>; renderPlantUml?(source:string,document:Document):SVGElement|string; maxSvgBytes?:number; maxSvgNodes?:number; }
export async function mountDiagramViewer(kind:'mermaid'|'plantuml',parsed:{source:string;warnings:string[]},input:ViewerInput,container:HTMLElement,_ctx:HostContext,options:DiagramMountOptions={}):Promise<ViewerHandle>{
 if(options.signal?.aborted)throw new MountAbortedError();const root:HTMLElement|ShadowRoot=options.styleIsolation!=='scoped'&&container.attachShadow?(container.shadowRoot??container.attachShadow({mode:'open'})):container;if(root===container)container.classList.add(VIEWER_ROOT_CLASS,`omni-viewer--${kind}`);else{const s=document.createElement('style');s.textContent=diagramViewerCss;root.append(s);}
 const shell=document.createElement('section');shell.className=`${VIEWER_ROOT_CLASS} omni-diagram omni-diagram--${kind}`;const header=document.createElement('header');header.className='omni-diagram__header';const title=document.createElement('div');title.className='omni-diagram__title';title.textContent=input.fileName;const meta=document.createElement('div');meta.textContent=kind==='mermaid'?'Mermaid':'PlantUML';header.append(title,meta);const stage=document.createElement('main');stage.className='omni-diagram__stage';stage.setAttribute('role','img');const warning=document.createElement('div');warning.className='omni-diagram__warning';warning.hidden=true;const sourceDetails=document.createElement('details');sourceDetails.className='omni-diagram__source-details';const sourceSummary=document.createElement('summary');sourceSummary.textContent='Source';const source=document.createElement('pre');source.className='omni-diagram__source';source.textContent=parsed.source;sourceDetails.append(sourceSummary,source);shell.append(header,stage,warning,sourceDetails);root.append(shell);let disposed=false;
 const show=(values:string[]):void=>{warning.hidden=values.length===0;warning.textContent=values.join('\n');};show(parsed.warnings);
 try{let svg:string|undefined;if(kind==='mermaid'&&options.renderMermaid)svg=await abortable(options.renderMermaid(`omni-mermaid-${nextId++}`,parsed.source),options.signal);else if(kind==='plantuml'&&options.renderPlantUml){const out=options.renderPlantUml(parsed.source,document);svg=typeof out==='string'?out:new XMLSerializer().serializeToString(out);}else{sourceDetails.open=true;show([...parsed.warnings,`${kind==='mermaid'?'Mermaid':'PlantUML'} renderer is not installed. The source is shown below.`]);}if(svg&&!disposed){const safe=sanitizeSvg(svg,options.maxSvgBytes??2_000_000,options.maxSvgNodes??20_000);stage.replaceChildren(safe);}}
 catch(error){sourceDetails.open=true;show([...parsed.warnings,`Diagram rendering failed: ${error instanceof Error?error.message:String(error)}`]);}
 if(options.signal?.aborted){disposed=true;shell.remove();throw new MountAbortedError();}return{dispose(){disposed=true;shell.remove();if(root===container)container.classList.remove(VIEWER_ROOT_CLASS,`omni-viewer--${kind}`);else root.replaceChildren();}};
}
let nextId=1;
export function sanitizeSvg(svg:string,maxBytes=2_000_000,maxNodes=20_000):SVGElement{if(new TextEncoder().encode(svg).byteLength>maxBytes)throw new Error('Rendered SVG exceeds the size limit.');const doc=new DOMParser().parseFromString(svg,'image/svg+xml');const root=doc.documentElement;if(root.localName!=='svg'||root.querySelector('parsererror'))throw new Error('Renderer returned invalid SVG.');const nodes=[root,...root.querySelectorAll('*')];if(nodes.length>maxNodes)throw new Error('Rendered SVG exceeds the node limit.');for(const node of nodes){if(['script','foreignObject','iframe','object','embed','audio','video','image','feImage','animate','set'].includes(node.localName)){node.remove();continue;}if(node.localName==='style'&&/(?:@import|url\s*\(|expression\s*\()/i.test(node.textContent??'')){node.remove();continue;}for(const attr of [...node.attributes]){const name=attr.name.toLowerCase(),value=attr.value.trim();if(name.startsWith('on')||name==='srcdoc'||/^javascript:/i.test(value)||/url\s*\(\s*(?!["']?#)/i.test(value)||name==='style'&&/url\s*\(/i.test(value)||['href','xlink:href'].includes(name)&&!value.startsWith('#'))node.removeAttribute(attr.name);}}return document.importNode(root,true) as unknown as SVGElement;}
function abortable<T>(promise:Promise<T>,signal?:AbortSignal):Promise<T>{if(!signal)return promise;if(signal.aborted)return Promise.reject(new MountAbortedError());return new Promise<T>((resolve,reject)=>{const abort=()=>reject(new MountAbortedError());signal.addEventListener('abort',abort,{once:true});promise.then(value=>{signal.removeEventListener('abort',abort);resolve(value);},error=>{signal.removeEventListener('abort',abort);reject(error);});});}
