export const diagramViewerCss = `
.omni-viewer--mermaid,.omni-viewer--plantuml{box-sizing:border-box;min-height:100%;padding:18px;display:flex;flex-direction:column;gap:14px;color:var(--omni-fg,#d4d4d4);background:var(--omni-bg,#1e1e1e);font:var(--omni-font-size,13px)/1.5 var(--omni-font-family,system-ui,sans-serif);--dg-border:var(--omni-border,#454545);--dg-muted:var(--omni-muted,#aaa);--dg-panel:var(--omni-panel-bg,rgba(127,127,127,.05))}
.omni-diagram *{box-sizing:border-box}.omni-diagram__header,.omni-diagram__toolbar,.omni-diagram__toolbar-group,.omni-diagram__panel-header{display:flex;align-items:center;gap:10px}.omni-diagram__header{align-items:flex-start;justify-content:space-between;gap:16px}.omni-diagram__title{font-size:16px;font-weight:600;margin-bottom:4px;word-break:break-word}.omni-diagram__summary,.omni-diagram__caption{color:var(--dg-muted);font-size:12px}.omni-diagram__status{padding:7px 10px;border-radius:999px;border:1px solid var(--dg-border);background:rgba(79,193,255,.16);font-size:12px;font-weight:600;white-space:nowrap}.omni-diagram__status.is-valid{background:rgba(46,160,67,.16);color:var(--omni-success,#3fb950)}.omni-diagram__status.is-invalid{background:rgba(244,71,71,.14);color:var(--omni-error,#f44747)}
.omni-diagram__toolbar{flex-wrap:wrap}.omni-diagram__toolbar-group{flex-wrap:wrap;padding:7px;border:1px solid var(--dg-border);border-radius:8px;background:var(--dg-panel)}.omni-diagram__button{cursor:pointer;border:1px solid var(--dg-border);background:var(--omni-button-secondary-bg,rgba(127,127,127,.16));color:inherit;border-radius:6px;padding:7px 10px;font:inherit}.omni-diagram__button:hover:not(:disabled){background:rgba(127,127,127,.26)}.omni-diagram__button--primary{background:var(--omni-accent,#0e639c);color:var(--omni-accent-fg,#fff);border-color:var(--omni-accent,#0e639c)}.omni-diagram__button.is-active{border-color:var(--omni-focus,#007fd4);background:color-mix(in srgb,var(--omni-focus,#007fd4) 22%,transparent)}.omni-diagram__button.is-dirty{border-color:var(--omni-warning,#cca700)}.omni-diagram__button:disabled{cursor:default;opacity:.5}.omni-diagram__zoom-label{min-width:52px;text-align:center;font-variant-numeric:tabular-nums;color:var(--dg-muted)}.omni-diagram__select{cursor:pointer;border:1px solid var(--dg-border);background:var(--omni-button-secondary-bg,rgba(127,127,127,.16));color:inherit;border-radius:6px;padding:6px 8px;font:inherit}
.omni-diagram__workspace{display:grid;grid-template-columns:minmax(360px,1fr);gap:14px;min-height:68vh}.omni-diagram__workspace.is-split{grid-template-columns:minmax(320px,1.1fr) minmax(300px,.9fr)}.omni-diagram__workspace.is-split .omni-diagram__source-panel{grid-column:2;grid-row:1}.omni-diagram__workspace.is-split .omni-diagram__stage-panel{grid-column:1;grid-row:1}.omni-diagram__panel{display:flex;flex-direction:column;min-height:0;border:1px solid var(--dg-border);border-radius:8px;background:var(--dg-panel);overflow:hidden}.omni-diagram__panel[hidden]{display:none}.omni-diagram__panel-header{justify-content:space-between;padding:12px 14px;border-bottom:1px solid var(--dg-border)}
.omni-diagram__stage{flex:1;min-height:0;overflow:auto;padding:18px;background:#fff;color:#111}.omni-diagram__stage-inner{transform-origin:top left;transition:transform .05s linear}.omni-diagram__stage svg{display:block;max-width:100%;height:auto;margin:0 auto}
.omni-diagram__stage.is-theme-dark{background:#1e1e1e;color:#eee}
.omni-diagram__source{flex:1;width:100%;min-height:62vh;resize:none;border:0;outline:0;padding:16px;background:var(--omni-editor-bg,var(--omni-bg,#1e1e1e));color:inherit;font:13px/1.55 var(--omni-mono,monospace);tab-size:4}
.omni-diagram__warning{padding:10px 12px;border:1px solid #b98b2f;border-radius:6px;background:rgba(185,139,47,.14);color:var(--omni-warning,#ffd98a);white-space:pre-wrap}.omni-diagram__warning[hidden]{display:none}.omni-diagram__message{padding:10px 12px;border:1px solid var(--omni-error,#f44747);border-radius:6px;color:var(--omni-error,#f44747);white-space:pre-wrap}.omni-diagram__message[hidden]{display:none}
@media(max-width:760px){.omni-diagram__workspace.is-split{grid-template-columns:1fr}.omni-diagram__workspace.is-split .omni-diagram__source-panel,.omni-diagram__workspace.is-split .omni-diagram__stage-panel{grid-column:1;grid-row:auto}}
`;
