export const latexViewerCss = `
.omni-viewer--latex{box-sizing:border-box;min-height:100%;padding:18px;display:flex;flex-direction:column;gap:14px;color:var(--omni-fg,#d4d4d4);background:var(--omni-bg,#1e1e1e);font:var(--omni-font-size,13px)/1.5 var(--omni-font-family,system-ui,sans-serif);--tex-border:var(--omni-border,#454545);--tex-muted:var(--omni-muted,#aaa);--tex-panel:var(--omni-panel-bg,rgba(127,127,127,.05))}
.omni-latex *{box-sizing:border-box}.omni-latex__header,.omni-latex__toolbar,.omni-latex__toolbar-group,.omni-latex__panel-header{display:flex;align-items:center;gap:10px}.omni-latex__header{align-items:flex-start;justify-content:space-between;gap:16px;flex-wrap:wrap}.omni-latex__title{font-size:16px;font-weight:600;margin-bottom:4px;word-break:break-word}.omni-latex__meta,.omni-latex__caption{color:var(--tex-muted);font-size:12px}
.omni-latex__status{padding:7px 10px;border-radius:999px;border:1px solid var(--tex-border);background:rgba(79,193,255,.16);font-size:12px;font-weight:600;white-space:nowrap}.omni-latex__status.is-valid{background:rgba(46,160,67,.16);color:var(--omni-success,#3fb950)}.omni-latex__status.is-invalid{background:rgba(244,71,71,.14);color:var(--omni-error,#f44747)}
.omni-latex__partial{display:inline-flex;align-items:center;gap:6px;padding:6px 10px;border:1px solid #b98b2f;border-radius:999px;background:rgba(185,139,47,.14);color:var(--omni-warning,#ffd98a);font-size:12px;font-weight:600}
.omni-latex__toolbar{flex-wrap:wrap}.omni-latex__toolbar-group{flex-wrap:wrap;padding:7px;border:1px solid var(--tex-border);border-radius:8px;background:var(--tex-panel)}.omni-latex__button{cursor:pointer;border:1px solid var(--tex-border);background:var(--omni-button-secondary-bg,rgba(127,127,127,.16));color:inherit;border-radius:6px;padding:7px 10px;font:inherit}.omni-latex__button:hover:not(:disabled){background:rgba(127,127,127,.26)}.omni-latex__button.is-active{border-color:var(--omni-focus,#007fd4);background:color-mix(in srgb,var(--omni-focus,#007fd4) 22%,transparent)}.omni-latex__button.is-dirty{border-color:var(--omni-warning,#cca700)}.omni-latex__button:disabled{cursor:default;opacity:.5}
/* Reading views are outline + one pane; split drops the outline and gives the
   preview and the editor an equal half each. */
.omni-latex__workspace{display:grid;grid-template-columns:minmax(200px,240px) minmax(320px,1fr);gap:14px;min-height:68vh}.omni-latex__workspace.is-split{grid-template-columns:minmax(280px,1fr) minmax(280px,1fr)}.omni-latex__panel{display:flex;flex-direction:column;min-height:0;border:1px solid var(--tex-border);border-radius:8px;background:var(--tex-panel);overflow:hidden}.omni-latex__panel[hidden]{display:none}.omni-latex__panel-header{justify-content:space-between;padding:12px 14px;border-bottom:1px solid var(--tex-border)}
.omni-latex__outline{flex:1;min-height:0;overflow:auto;padding:8px;margin:0;list-style:none}.omni-latex__outline-item{margin:0}.omni-latex__outline-link{display:block;width:100%;text-align:left;cursor:pointer;border:0;background:transparent;color:inherit;font:inherit;padding:5px 8px;border-radius:5px;word-break:break-word}.omni-latex__outline-link:hover{background:rgba(127,127,127,.18)}.omni-latex__outline-link.is-active{background:color-mix(in srgb,var(--omni-focus,#007fd4) 24%,transparent)}.omni-latex__outline-link[data-level="2"]{padding-left:20px}.omni-latex__outline-link[data-level="3"]{padding-left:32px}.omni-latex__outline-link[data-level="4"]{padding-left:44px}.omni-latex__outline-link[data-level="5"]{padding-left:56px}.omni-latex__outline-link[data-level="6"]{padding-left:68px}.omni-latex__outline-empty{padding:10px;color:var(--tex-muted)}
.omni-latex__preview{flex:1;min-height:0;overflow:auto;padding:22px 26px;background:var(--omni-editor-bg,var(--omni-bg,#1e1e1e))}.omni-latex__preview h1,.omni-latex__preview h2,.omni-latex__preview h3,.omni-latex__preview h4,.omni-latex__preview h5,.omni-latex__preview h6{margin:1.4em 0 .5em;line-height:1.3;scroll-margin-top:12px}.omni-latex__preview h1{font-size:1.7em}.omni-latex__preview h2{font-size:1.45em}.omni-latex__preview h3{font-size:1.25em}.omni-latex__preview p{margin:0 0 .9em}.omni-latex__preview ul,.omni-latex__preview ol{margin:0 0 .9em;padding-left:1.6em}.omni-latex__preview li{margin:.25em 0}
.omni-latex__math{display:block;margin:1em 0;padding:10px 12px;border-left:3px solid var(--omni-focus,#007fd4);background:rgba(127,127,127,.08);font:13px/1.5 var(--omni-mono,monospace);white-space:pre-wrap;overflow-x:auto}.omni-latex__math--inline{display:inline;margin:0;padding:1px 5px;border-left:0;border-radius:4px}
/* Once rendered the slot is KaTeX's own layout, so the source-code framing is
   dropped. Two things matter here beyond looks:
   - overflow is 'auto hidden', never 'auto'. A formula that is a pixel too wide
     raises a horizontal scrollbar, which eats content-box height, which raises a
     vertical scrollbar, which narrows the box, which keeps the horizontal one —
     a loop that puts both bars on a formula with room to spare.
   - line-height returns to normal. KaTeX sizes its own struts, and inheriting
     the body's 1.5 makes the rendered box taller than the line it sits on. */
.omni-latex__math.is-rendered{padding:.4em .2em;border-left:0;background:none;font:inherit;line-height:normal;white-space:normal;text-align:center;overflow:auto hidden}
.omni-latex__math--inline.is-rendered{padding:0;text-align:inherit;overflow:visible}.omni-latex__math.is-pending{opacity:.75}
/* A formula the engine refused is TeX source, not broken output — it keeps the
   source framing (mono, left aligned, muted) with a red rule to mark the
   failure. Colouring the whole block red reads as "this document is wrong". */
.omni-latex__math.is-invalid{border-left:3px solid var(--omni-error,#f44747);color:var(--tex-muted);text-align:left;font:12px/1.5 var(--omni-mono,monospace);white-space:pre-wrap;padding:10px 12px;background:rgba(244,71,71,.06)}
.omni-latex__math--inline.is-invalid{border-left:0;padding:1px 5px;text-decoration:underline wavy var(--omni-error,#f44747)}
/* Belt and braces for renderers that do not honour an errorColor option: KaTeX
   writes its error colour as an inline style, so overriding needs !important. */
.omni-latex__math .katex-error{color:var(--omni-warning,#cca700)!important;text-decoration:underline dotted}
.omni-latex__math .katex-display{margin:0;padding:0}.omni-latex__math .katex-display>.katex{max-width:100%}.omni-latex__math .katex{font-size:1.05em}
.omni-latex__cite{padding:0 3px;border-radius:4px;background:rgba(127,127,127,.18);color:var(--tex-muted);font-size:.92em}
.omni-latex__ref{padding:0 3px;border:0;border-radius:4px;background:rgba(127,127,127,.18);color:var(--tex-muted);font:inherit;font-size:.92em;cursor:pointer}.omni-latex__ref:hover{background:rgba(127,127,127,.3);color:var(--omni-fg,#d4d4d4)}
.omni-latex__preview .is-target{outline:2px solid var(--omni-focus,#007fd4);outline-offset:3px;border-radius:4px;transition:outline-color .3s}
.omni-latex__link{color:var(--omni-link,#4fc1ff);cursor:pointer;background:none;border:0;padding:0;font:inherit;text-decoration:underline}.omni-latex__link:disabled{cursor:default;text-decoration:none;color:inherit}
.omni-latex__include{margin:0 0 1em;padding-left:12px;border-left:2px dashed var(--tex-border)}.omni-latex__include-label{margin-bottom:.6em;color:var(--tex-muted);font-size:11px;font-weight:600;letter-spacing:.02em}
.omni-latex__table-wrap{margin:0 0 1em;overflow-x:auto}.omni-latex__table{border-collapse:collapse;min-width:min(100%,340px);font-size:.96em}.omni-latex__table th,.omni-latex__table td{border:1px solid var(--tex-border);padding:6px 10px;vertical-align:top}.omni-latex__table th{background:rgba(127,127,127,.12);font-weight:600;text-align:inherit}
.omni-latex__theorem{margin:0 0 1em;padding:12px 14px;border-left:3px solid var(--tex-border);background:rgba(127,127,127,.06);border-radius:0 6px 6px 0}.omni-latex__theorem-title{margin-bottom:.5em;font-weight:600}.omni-latex__theorem-note{margin-left:6px;font-weight:400;color:var(--tex-muted)}.omni-latex__theorem-body{font-style:italic}.omni-latex__theorem-body p:last-child{margin-bottom:0}
.omni-latex__verbatim{margin:0 0 .9em;padding:12px 14px;border:1px solid var(--tex-border);border-radius:6px;background:rgba(127,127,127,.08);font:12px/1.5 var(--omni-mono,monospace);white-space:pre;overflow-x:auto}
.omni-latex__unsupported{margin:0 0 .9em;border:1px dashed var(--tex-border);border-radius:6px;background:rgba(127,127,127,.06);overflow:hidden}.omni-latex__badge{display:block;padding:6px 12px;border-bottom:1px dashed var(--tex-border);color:var(--omni-warning,#ffd98a);font-size:11px;font-weight:600;letter-spacing:.02em}.omni-latex__unsupported pre{margin:0;padding:12px 14px;font:12px/1.5 var(--omni-mono,monospace);white-space:pre-wrap;overflow-x:auto;color:var(--tex-muted)}.omni-latex__unsupported--inline{display:inline;border:0;background:none;padding:0 2px;color:var(--tex-muted);font:12px/1.5 var(--omni-mono,monospace)}
.omni-latex__float{margin:0 0 .9em;padding:12px 14px;border:1px dashed var(--tex-border);border-radius:6px;text-align:center;color:var(--tex-muted)}.omni-latex__float-caption{color:var(--omni-fg,#d4d4d4)}
.omni-latex__source{flex:1;width:100%;min-height:62vh;resize:none;border:0;outline:0;padding:16px;background:var(--omni-editor-bg,var(--omni-bg,#1e1e1e));color:inherit;font:13px/1.55 var(--omni-mono,monospace);tab-size:4}
.omni-latex__warning{padding:10px 12px;border:1px solid #b98b2f;border-radius:6px;background:rgba(185,139,47,.14);color:var(--omni-warning,#ffd98a);white-space:pre-wrap}.omni-latex__warning[hidden]{display:none}.omni-latex__message{padding:10px 12px;border:1px solid var(--omni-error,#f44747);border-radius:6px;color:var(--omni-error,#f44747);white-space:pre-wrap}.omni-latex__message[hidden]{display:none}
@media(max-width:900px){.omni-latex__workspace,.omni-latex__workspace.is-split{grid-template-columns:1fr}}
`;
