// @ts-nocheck -- OOXML's sparse optional attributes are normalized at the public boundary.
import {DEFAULT_LIMITS,LimitTracker,type Diagnostic,type ParseOptions,type ParseOutcome} from '../types.js';
import type {Slide,SlideDeck,SlideElement,SlideParagraph} from '../slide-model.js';
export * from '../slide-model.js';
export interface PptxZipReader { list():Promise<readonly string[]>;text(path:string):Promise<string|undefined>;bytes(path:string):Promise<Uint8Array|undefined>;close?():void|Promise<void>; }
export interface PptxParserDeps { openZip(data:Uint8Array,options?:ParseOptions):Promise<PptxZipReader>; }
export {openPptxZip} from './zip-reader.js';
export {parsePptxVscode} from './vscode.js';
const EMU_PER_PX=9525; const DEFAULT_SIZE={widthPx:1280,heightPx:720};
const attr=(tag:string,name:string)=>new RegExp(`(?:^|\\s)${name}="([^"]*)"`).exec(tag)?.[1];
const xmlText=(value:string)=>value.replace(/<a:br\s*\/?\s*>/g,'\n').replace(/<[^>]+>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&apos;/g,"'");
function relationships(xml:string,part:string):Map<string,string>{const out=new Map<string,string>();const dir=part.slice(0,part.lastIndexOf('/'));for(const tag of xml.match(/<Relationship\b[^>]*>/g)??[]){const id=attr(tag,'Id'),target=attr(tag,'Target');if(!id||!target||target.startsWith('http:')||target.startsWith('https:'))continue;const pieces=`${dir}/${target}`.split('/');const resolved:string[]=[];for(const p of pieces){if(p==='..')resolved.pop();else if(p!=='.'&&p)resolved.push(p);}out.set(id,resolved.join('/'));}return out;}
function transform(block:string){const xfrm=/<a:xfrm\b[^>]*>([\s\S]*?)<\/a:xfrm>/.exec(block)?.[0]??'';const off=/<a:off\b[^>]*>/.exec(xfrm)?.[0]??'';const ext=/<a:ext\b[^>]*>/.exec(xfrm)?.[0]??'';return{x:Number(attr(off,'x')??0)/EMU_PER_PX,y:Number(attr(off,'y')??0)/EMU_PER_PX,width:Number(attr(ext,'cx')??0)/EMU_PER_PX,height:Number(attr(ext,'cy')??0)/EMU_PER_PX,rotateDeg:Number(attr(/<a:xfrm\b[^>]*>/.exec(xfrm)?.[0]??'','rot')??0)/60000};}
function color(block:string,fallback?:string){const value=/<a:srgbClr\b[^>]*val="([0-9A-Fa-f]{6})"/.exec(block)?.[1];return value?`#${value.toLowerCase()}`:fallback;}
function paragraphs(block:string):SlideParagraph[]{return (block.match(/<a:p\b[\s\S]*?<\/a:p>/g)??[]).map(p=>{const runs=(p.match(/<a:r\b[\s\S]*?<\/a:r>/g)??[]).map(r=>{const text=xmlText(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/.exec(r)?.[1]??'');const rpr=/<a:rPr\b[^>]*>/.exec(r)?.[0]??'';return{text,...(attr(rpr,'sz')?{fontSizePx:Number(attr(rpr,'sz'))/75}:{}),...(attr(rpr,'b')==='1'?{bold:true}:{}),...(attr(rpr,'i')==='1'?{italic:true}:{}),...(color(r)?{color:color(r)}:{})};});const ppr=/<a:pPr\b[^>]*>/.exec(p)?.[0]??'';const text=runs.length?runs.map(r=>r.text).join(''):xmlText(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/.exec(p)?.[1]??'');return{text,level:Number(attr(ppr,'lvl')??0),...(/<a:bu(?:Char|AutoNum)\b/.test(p)?{bullet:true}:{}),...(attr(ppr,'algn')?{align:attr(ppr,'algn')}:{}),runs};}).filter(p=>p.text.length>0);}
async function parseSlide(zip:PptxZipReader,path:string,n:number,size:{widthPx:number;heightPx:number}):Promise<Slide>{const xml=await zip.text(path)??'';const relPath=`${path.slice(0,path.lastIndexOf('/'))}/_rels/${path.slice(path.lastIndexOf('/')+1)}.rels`;const rels=relationships(await zip.text(relPath)??'',path);const elements:SlideElement[]=[];let z=0;for(const block of xml.match(/<p:(?:sp|pic|graphicFrame)\b[\s\S]*?<\/p:(?:sp|pic|graphicFrame)>/g)??[]){const frame=transform(block);const common={...frame,zIndex:z++};if(block.startsWith('<p:pic')){const rid=/<a:blip\b[^>]*r:embed="([^"]+)"/.exec(block)?.[1];const target=rid?rels.get(rid):undefined;const data=target?await zip.bytes(target):undefined;if(data){let binary='';for(const b of data)binary+=String.fromCharCode(b);const ext=target?.split('.').pop()?.toLowerCase();const mime=ext==='png'?'image/png':ext==='svg'?'image/svg+xml':'image/jpeg';elements.push({...common,type:'image',src:`data:${mime};base64,${btoa(binary)}`});}continue;}if(block.startsWith('<p:graphicFrame')){const rows=(block.match(/<a:tr\b[\s\S]*?<\/a:tr>/g)??[]).map(r=>(r.match(/<a:tc\b[\s\S]*?<\/a:tc>/g)??[]).map(c=>xmlText((c.match(/<a:t\b[^>]*>([\s\S]*?)<\/a:t>/g)??[]).join(' '))));if(rows.length)elements.push({...common,type:'table',tableRows:rows});continue;}const ps=paragraphs(block);const geom=/<a:prstGeom\b[^>]*prst="([^"]+)"/.exec(block)?.[1];if(ps.length)elements.push({...common,type:'text',paragraphs:ps,isTitle:/<p:ph\b[^>]*type="(?:title|ctrTitle)"/i.test(block)});else elements.push({...common,type:'shape',presetGeom:geom,fillColor:color(block,'transparent'),borderColor:color(/<a:ln\b[\s\S]*?<\/a:ln>/.exec(block)?.[0]??'')});}return{slideNumber:n,...size,backgroundColor:color(/<p:bg\b[\s\S]*?<\/p:bg>/.exec(xml)?.[0]??'','#ffffff')??'#ffffff',elements};}
export async function parsePptx(input:Uint8Array,deps:PptxParserDeps,options:ParseOptions={}):Promise<ParseOutcome<SlideDeck>>{const started=Date.now(),diagnostics:Diagnostic[]=[];if(input.byteLength>(options.limits?.maxInputBytes??50*1024*1024))return{result:{status:'failed',failure:{code:'limit-exceeded',retryable:false,messageKey:'diag.limit-exceeded.input'},diagnostics},execution:{workerUsed:false,hardLimitEnforced:false,elapsedMillis:Date.now()-started}};let zip:PptxZipReader|undefined;try{zip=await deps.openZip(input,options);const presentation=await zip.text('ppt/presentation.xml');if(!presentation)throw new Error('presentation');const sz=/<p:sldSz\b[^>]*>/.exec(presentation)?.[0]??'';const size=attr(sz,'cx')&&attr(sz,'cy')?{widthPx:Number(attr(sz,'cx'))/EMU_PER_PX,heightPx:Number(attr(sz,'cy'))/EMU_PER_PX}:DEFAULT_SIZE;const rels=relationships(await zip.text('ppt/_rels/presentation.xml.rels')??'','ppt/presentation.xml');let paths=(presentation.match(/<p:sldId\b[^>]*r:id="([^"]+)"/g)??[]).map(t=>rels.get(/r:id="([^"]+)"/.exec(t)?.[1]??'')).filter((x):x is string=>!!x);if(!paths.length)paths=(await zip.list()).filter(x=>/^ppt\/slides\/slide\d+\.xml$/i.test(x)).sort((a,b)=>Number(/slide(\d+)/i.exec(a)?.[1])-Number(/slide(\d+)/i.exec(b)?.[1]));const tracker=new LimitTracker({...DEFAULT_LIMITS,...options.limits},options.signal);const slides:Slide[]=[];for(const path of paths){tracker.addEntries(1);const violation=tracker.checkpoint();if(violation){diagnostics.push({severity:'warning',code:'limit-exceeded',messageKey:violation.kind==='aborted'?'diag.aborted':'diag.ppt.limit-exceeded'});break;}slides.push(await parseSlide(zip,path,slides.length+1,size));}const deck={slides,totalSlides:slides.length,slideSize:size};return{result:{status:slides.length===paths.length?'ok':'partial',document:deck,diagnostics},execution:{workerUsed:false,hardLimitEnforced:false,elapsedMillis:Date.now()-started}};}catch{return{result:{status:'failed',failure:{code:'invalid-format',retryable:false,messageKey:'diag.ppt.invalid-format'},diagnostics},execution:{workerUsed:false,hardLimitEnforced:false,elapsedMillis:Date.now()-started}};}finally{await zip?.close?.();}}
