import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { Buffer } from 'node:buffer';
import { gunzipSync } from 'node:zlib';
import { describe, expect, it } from 'vitest';
import { Hdf5Parser, readHdf5Objects } from './index.js';
import { parseHdf5File } from './node.js';

// Real HDF5 files produced by the HDF5 C library (h5cc).
//  - DEFAULT: superblock version 0 (classic B-tree + local heap + symbol table groups)
//  - LATEST:  superblock version 3 (version-2 object headers with compact link messages)
// Both contain: group /measurements with dataset temperature {3,4} float64,
// and a root dataset /ids {5} int32.
const DEFAULT_H5_BASE64 =
    'iUhERg0KGgoAAAAAAAgIAAQAEAAAAAAAAAAAAAAAAAD//////////5ASAAAAAAAA//////////8AAAAAAAAAAGAAAAAAAAAAAQAA' +
    'AAAAAACIAAAAAAAAAKgCAAAAAAAAAQABAAEAAAAYAAAAAAAAABEAEAAAAAAAiAAAAAAAAACoAgAAAAAAAFRSRUUAAAEA////////' +
    '/////////////wAAAAAAAAAA4AUAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAABIRUFQAAAAAFgAAAAAAAAAIAAAAAAAAADIAgAAAAAAAAAAAAAAAAAAbWVhc3VyZW1lbnRzAAAAAGlkcwAAAAAAAQAAAAAA' +
    'AAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAQAAABgAAAAAAAAAEQAQAAAAAABI' +
    'AwAAAAAAAGgFAAAAAAAAVFJFRQAAAQD/////////////////////AAAAAAAAAAA4CAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEhFQVAAAAAAWAAAAAAAAAAYAAAAAAAAAIgFAAAAAAAAAAAAAAAAAAB0' +
    'ZW1wZXJhdHVyZQAAAAAAAQAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAFNOT0QBAAIAGAAAAAAAAACAEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAIAMAAAAAAAABAAAAAAAA' +
    'AEgDAAAAAAAAaAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAYAAQAAAAABAAAAAAAAAQAoAAAAAAABAgEAAAAAAAMAAAAAAAAABAAA' +
    'AAAAAAADAAAAAAAAAAQAAAAAAAAAAwAYAAEAAAARID8ACAAAAAAAQAA0CwA0/wMAAAAAAAAFAAgAAQAAAAICAgEAAAAACAAYAAAA' +
    'AAADAYAJAAAAAAAAYAAAAAAAAAAAAAAAAAASAAgAAAAAAAEAAAAN5D5qAABoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAFNOT0QBAAEACAAAAAAAAAAoBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPg/AAAAAAAACEAAAAAAAAASQAAAAAAAABhAAAAA' +
    'AAAAHkAAAAAAAAAiQAAAAAAAACVAAAAAAAAAKEAAAAAAAAArQAAAAAAAAC5AAAAAAACAMEABAAAAAgAAAAMAAAAEAAAABQAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEABgABAAAAAAEAAAAAAAABABgA' +
    'AAAAAAEBAQAAAAAABQAAAAAAAAAFAAAAAAAAAAMAEAABAAAAEAgAAAQAAAAAACAAAAAAAAUACAABAAAAAgICAQAAAAAIABgAAAAA' +
    'AAMB4AkAAAAAAAAUAAAAAAAAAAAAAAAAABIACAAAAAAAAQAAAA3kPmoAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';
const LATEST_H5_BASE64 =
    'iUhERg0KGgoDCAgAAAAAAAAAAAD//////////3QIAAAAAAAAMAAAAAAAAAD3ES0dT0hEUgIgIeQ+aiHkPmoh5D5qIeQ+angCEgAA' +
    'AAD/////////////////////CgIAAQAABhcAAAEADG1lYXN1cmVtZW50c8MAAAAAAAAABg4AAAEAA2lkc3ICAAAAAAAAACsAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF5glxT0hEUgIgIeQ+aiHkPmoh5D5qIeQ+angCEgAAAAD/' +
    '////////////////////CgIAAQAABhYAAAEAC3RlbXBlcmF0dXJlVgEAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC3SC/sT0hEUgIhIeQ+aiHkPmoh5D5qIeQ+agABASQAAAICAQED' +
    'AAAAAAAAAAQAAAAAAAAAAwAAAAAAAAAEAAAAAAAAAAMUAAERID8ACAAAAAAAQAA0CwA0/wMAAAUCAAEDCggSAAAEAQAIAAAAAAAA' +
    'YAAAAAAAAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZietPSERSAiEh5D5qIeQ+aiHkPmoh5D5qAAEBFAAAAgEBAQUAAAAAAAAABQAAAAAAAAAD' +
    'DAABEAgAAAQAAAAAACAABQIAAQMKCBIAAAQBYAgAAAAAAAAUAAAAAAAAAAC4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAA7sqapAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPg/AAAAAAAACEAAAAAAAAASQAAAAAAAABhAAAAAAAAAHkAAAAAA' +
    'AAAiQAAAAAAAACVAAAAAAAAAKEAAAAAAAAArQAAAAAAAAC5AAAAAAACAMEABAAAAAgAAAAMAAAAEAAAABQAAAA==';

// Written by h5py 3.16 (gzipped: HDF5 files are mostly zero padding). Root
// attributes cover every decoded datatype — a variable-length UTF-8 string
// stored in the global heap, a fixed-length string array, signed and unsigned
// integers of both byte orders, and a float — plus a dataset attribute.
const ATTRIBUTES_H5_GZIP =
    'H4sIAA75fmoC/+2UMU/CQBTH7wrICRghkoAudjRODAxuYARlMGLUwU0LVGjStIZeZx1190M4OvoR/AiOxslvgb3ea+lVTUicjO+3PK5373/v' +
    'Pd69+15nf6WwUSACxkiWlEmSGdCoq+to/xIsBXsH9lGLvrNwD9wDdamvZ+T6GRzPTrpdcXqWIrrnIyctI8h/pNfdPRb2PO4jyYumnhsZ3Ej2' +
    'Y++X91bgpnRfl0gb+jtHqkFXOi43xXqd0tCjHMfAlPdRTTQxTemw4JVwY+yJ9VqwKVqeUukZpRlZw76eGANTJhvqNEBnKfjNyND1HS7iYNF1' +
    'bSWO7dhvJ/YTeUwNbrkib70V+zWLpDnLqO9c8tYqQYUpKQZadTKwxhemM7IMB/6nZRLMlPDFy3M/5APS2rweS6HelS0L8qWeoANhxZbCKeFP' +
    'EwFTsiWtpvplU/7zdT10reibcfw1Rmo3sJ+DuaZpUpDBhMvQaNQ1lEol8xJ19h2Lewv0Sz7RL9o3uotyetTv0HAaS16zOFMQQg72+oc0MVCV' +
    'ORUwMW3b1d9vH3SD86k18LnpJd9tHuzQtD3L92Ldp1WsLYIgCIIgCIIgCIL8VT4Bsj5NoTAYAAA=';

function tableRows(model: ReturnType<typeof Hdf5Parser.parse>, prefix: string): Array<Array<string | number>> {
    const table = model.tables.find(entry => entry.title.startsWith(prefix));
    if (!table) {
        throw new Error(`Missing table: ${prefix}`);
    }
    return table.rows;
}

describe('Hdf5Parser', () => {
    it('enumerates groups and datasets from a version 0 superblock file', () => {
        const buffer = Buffer.from(DEFAULT_H5_BASE64, 'base64');
        const model = Hdf5Parser.parse(buffer, `${buffer.length} bytes`);

        expect(model.format).toBe('HDF5');
        expect(model.summary).toContainEqual({ label: 'Superblock version', value: 0 });
        expect(model.summary).toContainEqual({ label: 'Datasets', value: 2 });
        expect(model.summary).toContainEqual({ label: 'Groups', value: 2 });

        const datasets = tableRows(model, 'Datasets');
        expect(datasets).toContainEqual(['/ids', '5', 'Integer32', 4]);
        expect(datasets).toContainEqual(['/measurements/temperature', '3 × 4', 'Float64', 8]);

        const groups = tableRows(model, 'Groups').map(row => row[0]);
        expect(groups).toEqual(expect.arrayContaining(['/', '/measurements']));
    });

    it('enumerates groups and datasets from a version 3 superblock file', () => {
        const buffer = Buffer.from(LATEST_H5_BASE64, 'base64');
        const model = Hdf5Parser.parse(buffer, `${buffer.length} bytes`);

        expect(model.summary).toContainEqual({ label: 'Superblock version', value: 3 });
        const datasets = tableRows(model, 'Datasets');
        expect(datasets).toContainEqual(['/ids', '5', 'Integer32', 4]);
        expect(datasets).toContainEqual(['/measurements/temperature', '3 × 4', 'Float64', 8]);
    });

    it('reports a warning when the signature is missing', () => {
        const buffer = Buffer.from('not an hdf5 file at all, just text padding bytes here', 'utf8');
        const model = Hdf5Parser.parse(buffer, `${buffer.length} bytes`);

        expect(model.summary).toContainEqual({ label: 'Signature', value: 'not found' });
        expect(model.warnings.join(' ')).toContain('does not start with the expected HDF5 signature');
    });

    it('reads metadata from a file on disk via random access (parseFile)', () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'omni-hdf5-'));
        const filePath = path.join(tempDir, 'sample.h5');
        // The trailing zero padding stands in for a much larger dataset payload that is
        // never read: parseFile only seeks to the small, scattered metadata regions.
        const file = Buffer.concat([Buffer.from(DEFAULT_H5_BASE64, 'base64'), Buffer.alloc(1024 * 1024)]);
        fs.writeFileSync(filePath, file);

        try {
            const model = parseHdf5File(filePath, `${file.length} bytes`);

            expect(model.summary).toContainEqual({ label: 'Superblock version', value: 0 });
            const datasets = tableRows(model, 'Datasets');
            expect(datasets).toContainEqual(['/ids', '5', 'Integer32', 4]);
            expect(datasets).toContainEqual(['/measurements/temperature', '3 × 4', 'Float64', 8]);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it('decodes group and dataset attributes, including global-heap strings', () => {
        const objects = readHdf5Objects(new Uint8Array(gunzipSync(Buffer.from(ATTRIBUTES_H5_GZIP, 'base64'))));

        expect(objects.warnings).toEqual([]);
        expect(objects.truncated).toBe(false);
        const root = objects.objects.find(object => object.path === '/');
        const attribute = (name: string): unknown => root?.attributes.find(entry => entry.name === name);

        expect(attribute('note')).toMatchObject({ shape: [], values: ['hello — attributes'], truncated: false });
        expect(attribute('tags')).toMatchObject({ type: 'String', shape: [2], values: ['alpha', 'beta'] });
        expect(attribute('count')).toMatchObject({ type: 'Integer64', values: [42] });
        expect(attribute('ratio')).toMatchObject({ type: 'Float64', values: [0.5] });
        expect(attribute('big_endian')).toMatchObject({ type: 'Integer32', values: [1, 2] });
        expect(attribute('flags')).toMatchObject({ type: 'Integer8', values: [1, 0, 1] });

        const dataset = objects.objects.find(object => object.path === '/data');
        expect(dataset).toMatchObject({ kind: 'Dataset', dimensions: [3, 4], type: 'Float32', elementSize: 4 });
        expect(dataset?.attributes).toEqual([
            { name: 'units', type: 'Variable-length', shape: [], values: ['celsius'], truncated: false }
        ]);
    });

    it('returns an empty attribute list for objects that carry none', () => {
        const buffer = Buffer.from(DEFAULT_H5_BASE64, 'base64');
        const objects = readHdf5Objects(new Uint8Array(buffer));

        expect(objects.objects.map(object => object.path)).toContain('/measurements/temperature');
        expect(objects.objects.every(object => object.attributes.length === 0)).toBe(true);
    });
});
