import{describe,expect,it}from'vitest';import{parseA2l,parseArxml,parseAsc,parseBlf,parseMf4,parsePcap,parsePcapng}from'./index.js';import{parseDbc}from'../dbc/index.js';
const enc=(x:string)=>new TextEncoder().encode(x);
function pcapngSection(little:boolean):Uint8Array{const data=new Uint8Array(28);const v=new DataView(data.buffer);data.set([0x0a,0x0d,0x0d,0x0a]);v.setUint32(4,28,little);data.set(little?[0x4d,0x3c,0x2b,0x1a]:[0x1a,0x2b,0x3c,0x4d],8);v.setUint16(12,1,little);v.setUint16(14,0,little);v.setBigInt64(16,-1n,little);v.setUint32(24,28,little);return data;}
function pcapngInterface(little:boolean):Uint8Array{const data=new Uint8Array(20);const v=new DataView(data.buffer);v.setUint32(0,1,little);v.setUint32(4,20,little);v.setUint16(8,1,little);v.setUint32(12,65535,little);v.setUint32(16,20,little);return data;}
function concat(...values:Uint8Array[]):Uint8Array{const result=new Uint8Array(values.reduce((sum,value)=>sum+value.length,0));let offset=0;for(const value of values){result.set(value,offset);offset+=value.length;}return result;}
describe('independent automotive parsers',()=>{
it('parses DBC messages/signals and reports invalid/truncated input',()=>{const m=parseDbc(enc('VERSION "1"\nBU_: ECU\nBO_ 100 Msg: 8 ECU\n SG_ Speed : 0|16@1+ (0.1,0) [0|250] "km/h" ECU'));expect(m.stats).toMatchObject({messageCount:1,signalCount:1});expect(parseDbc(enc('SG_ Orphan : 0|8@1+ (1,0) [0|1] "" ECU')).warnings.join(' ')).toContain('before any message');expect(parseDbc(enc('BO_ 1 A: 8 E\nSG_'),{maxBytes:12}).warnings.join(' ')).toContain('limited');});
it('separates DBC bit-31 extended-frame flags from the actual CAN ID',()=>{const encoded=2566842624;const m=parseDbc(enc(`BO_ ${encoded} Extended: 8 ECU\n SG_ State : 0|8@1+ (1,0) [0|1] "" ECU\nCM_ BO_ ${encoded} "extended comment";\nVAL_ ${encoded} State 0 "Off" 1 "On";`));expect(m.messages[0]).toMatchObject({encodedId:encoded,id:0x18fee900,idHex:'0x18FEE900',isExtended:true,comment:'extended comment'});expect(m.messages[0]?.signals[0]?.values).toEqual([{value:0,label:'Off'},{value:1,label:'On'}]);expect(m.stats.extendedMessageCount).toBe(1);});
it('parses ARXML, A2L, and ASC with bounded previews',()=>{expect(parseArxml(enc('<AUTOSAR xmlns="urn:x"><AR-PACKAGE><SHORT-NAME>P</SHORT-NAME></AR-PACKAGE></AUTOSAR>')).summary[0]?.value).toBe(1);expect(parseArxml(enc('<x/>')).warnings.length).toBeGreaterThan(0);expect(parseA2l(enc('/begin PROJECT Demo\n/begin MEASUREMENT RPM')).summary[0]?.value).toBe(2);expect(parseA2l(enc('/beg')).warnings.length).toBeGreaterThan(0);expect(parseAsc(enc('date today\n0.001 1 123 Rx d 8 00 01')).summary[0]?.value).toBe(1);expect(parseAsc(enc('date only')).warnings.length).toBeGreaterThan(0);});
it('parses ASC IDs and CAN FD columns from their format-defined positions',()=>{const model=parseAsc(enc('0.001 123 1AB Rx d 8 00 01\n30.300981 CANFD 3 Tx 50005x 0 1 5 0 140000 73 200050\n31.000000 CANFD 4 Rx 123 EngineStatus 1 0 9 12 00 01 02 03 04 05 06 07 08 09 0A 0B 140000 73 200050'));expect(model.tables[1]?.rows).toEqual([['0.001','CAN','123','Rx','1AB','8','00 01',1],['30.300981','CANFD','3','Tx','50005x','5','',2],['31.000000','CANFD','4','Rx','123','9','00 01 02 03 04 05 06 07 08 09 0A 0B',3]]);});
it('parses BLF and MF4 headers and warns on bad or truncated signatures',()=>{const blf=new Uint8Array(144);const v=new DataView(blf.buffer);blf.set(enc('LOGG'));v.setUint32(4,144,true);blf[8]=5;v.setUint32(32,7,true);v.setUint32(128,99,true);const parsed=parseBlf(blf);expect(parsed.warnings).toHaveLength(0);expect(parsed.summary.find(item=>item.label==='Application ID')?.value).toBe(5);expect(parsed.summary.find(item=>item.label==='Object count hint')?.value).toBe(7);expect(parseBlf(enc('LOGG')).warnings.join(' ')).toContain('truncated');expect(parseBlf(enc('BAD!')).warnings.length).toBe(1);const mf4=new Uint8Array(64);mf4.set(enc('MDF     4.10    TEST    ##HD'));expect(parseMf4(mf4).summary[0]?.value).toBe('MDF');expect(parseMf4(enc('MDF     ')).warnings.join(' ')).toContain('truncated');expect(parseMf4(enc('bad')).warnings.length).toBeGreaterThan(0);});
it('parses PCAP packets and stops safely on truncated records',()=>{const data=new Uint8Array(24+16+4);const v=new DataView(data.buffer);data.set([0xd4,0xc3,0xb2,0xa1]);v.setUint16(4,2,true);v.setUint16(6,4,true);v.setUint32(20,1,true);v.setUint32(24,1,true);v.setUint32(32,4,true);v.setUint32(36,4,true);data.set([1,2,3,4],40);expect(parsePcap(data).tables[0]?.rows).toHaveLength(1);expect(parsePcap(data.subarray(0,data.length-2)).warnings.join(' ')).toContain('truncated');expect(parsePcap(enc('bad')).warnings.join(' ')).toContain('valid PCAP');});
it('parses PCAPNG blocks and detects malformed blocks',()=>{const data=new Uint8Array(28);const v=new DataView(data.buffer);data.set([0x0a,0x0d,0x0d,0x0a]);v.setUint32(4,28,true);data.set([0x4d,0x3c,0x2b,0x1a],8);v.setUint16(12,1,true);v.setUint16(14,0,true);v.setUint32(24,28,true);expect(parsePcapng(data).warnings).toHaveLength(0);expect(parsePcapng(data.subarray(0,20)).warnings.join(' ')).toContain('truncated');expect(parsePcapng(enc('bad')).warnings.join(' ')).toContain('valid PCAPNG');});
it('re-detects byte order at every PCAPNG section header',()=>{const model=parsePcapng(concat(pcapngSection(true),pcapngInterface(true),pcapngSection(false),pcapngInterface(false)));expect(model.warnings).toHaveLength(0);const counts=model.tables.find(table=>table.title==='Block counts')?.rows;expect(counts).toContainEqual(['0x0a0d0d0a',2]);expect(counts).toContainEqual(['0x00000001',2]);});});
