// @vitest-environment jsdom
import {describe,expect,it,vi} from 'vitest';import JSZip from 'jszip';import type {HostContext} from '../../host/index.js';import type {PdfJsModule} from '../pdf/index.js';import {mountPptViewer} from './index.js';
HTMLCanvasElement.prototype.getContext=vi.fn(()=>null) as unknown as typeof HTMLCanvasElement.prototype.getContext;
const ctx:HostContext={assets:{resolveAssetUrl:async value=>value},i18n:{t:key=>key},logger:{log(){}}};
const pdfjs:PdfJsModule={GlobalWorkerOptions:{workerSrc:''},TextLayer:class{render(){return Promise.resolve();}cancel(){}},getDocument:()=>({promise:Promise.resolve({numPages:0,getPage:async()=>{throw new Error('no pages');},destroy:async()=>{}}),destroy(){}})};
describe('PPT PDF fallback',()=>{
it('converts a parser failure and mounts the shared PDF renderer',async()=>{const convertToPdf=vi.fn(async()=>new Uint8Array([0x25,0x50,0x44,0x46,0x2d]));const container=document.createElement('div');const handle=await mountPptViewer({fileName:'legacy.ppt',data:new Uint8Array([1,2,3])},container,ctx,{convertToPdf,loadPdfjs:async()=>pdfjs},{styleIsolation:'scoped'});expect(convertToPdf).toHaveBeenCalledOnce();expect(handle.mode).toBe('pdf');expect(container.querySelector('.omni-pdf')).not.toBeNull();handle.dispose();});
it('converts a valid PPTX that contains zero slides',async()=>{const zip=new JSZip();zip.file('ppt/presentation.xml','<p:presentation xmlns:p="p"><p:sldIdLst/><p:sldSz cx="9144000" cy="6858000"/></p:presentation>');const bytes=new Uint8Array(await zip.generateAsync({type:'uint8array'}));const convertToPdf=vi.fn(async()=>new Uint8Array([0x25,0x50,0x44,0x46,0x2d]));const handle=await mountPptViewer({fileName:'empty.pptx',data:bytes},document.createElement('div'),ctx,{convertToPdf,loadPdfjs:async()=>pdfjs},{styleIsolation:'scoped'});expect(convertToPdf).toHaveBeenCalledOnce();expect(handle.mode).toBe('pdf');handle.dispose();});
it('converts a PPTX with slides but no renderable elements',async()=>{const zip=new JSZip();zip.file('ppt/presentation.xml','<p:presentation xmlns:p="p" xmlns:r="r"><p:sldIdLst><p:sldId r:id="r1"/></p:sldIdLst><p:sldSz cx="9144000" cy="6858000"/></p:presentation>');zip.file('ppt/_rels/presentation.xml.rels','<Relationships><Relationship Id="r1" Type="slide" Target="slides/slide1.xml"/></Relationships>');zip.file('ppt/slides/slide1.xml','<p:sld xmlns:p="p"><p:cSld><p:spTree/></p:cSld></p:sld>');const bytes=new Uint8Array(await zip.generateAsync({type:'uint8array'}));const convertToPdf=vi.fn(async()=>new Uint8Array([0x25,0x50,0x44,0x46,0x2d]));const handle=await mountPptViewer({fileName:'empty-elements.pptx',data:bytes},document.createElement('div'),ctx,{convertToPdf,loadPdfjs:async()=>pdfjs},{styleIsolation:'scoped'});expect(convertToPdf).toHaveBeenCalledOnce();expect(handle.mode).toBe('pdf');handle.dispose();});
it('tries the lightweight PPTX extractor before requiring PDF conversion',async()=>{const zip=new JSZip();zip.file('ppt/presentation.xml','<p:presentation xmlns:p="p" xmlns:r="r"><p:sldIdLst><p:sldId r:id="r1"/></p:sldIdLst><p:sldSz cx="9144000" cy="6858000"/></p:presentation>');zip.file('ppt/_rels/presentation.xml.rels','<Relationships><Relationship Id="r1" Type="slide" Target="slides/slide1.xml"/></Relationships>');zip.file('ppt/slides/slide1.xml','<p:sld xmlns:p="p"><p:cSld><p:spTree/></p:cSld></p:sld>');const bytes=new Uint8Array(await zip.generateAsync({type:'uint8array'})),parseLegacyPptx=vi.fn(async()=>({result:{status:'ok' as const,document:{totalSlides:1,slides:[{slideNumber:1,widthPx:960,heightPx:720,backgroundColor:'#fff',elements:[{type:'text' as const,x:10,y:10,width:300,height:40,zIndex:0,paragraphs:[{text:'Recovered',level:0}]}]}]},diagnostics:[]},execution:{workerUsed:false,hardLimitEnforced:false,elapsedMillis:0}}));const container=document.createElement('div'),handle=await mountPptViewer({fileName:'legacy-recoverable.pptx',data:bytes},container,ctx,{parseLegacyPptx},{styleIsolation:'scoped'});expect(parseLegacyPptx).toHaveBeenCalledOnce();expect(handle.mode).toBe('slides');expect(container.textContent).toContain('Recovered');handle.dispose();});
it('keeps the parser failure when no converter is installed',async()=>{await expect(mountPptViewer({fileName:'bad.ppt',data:new Uint8Array([1])},document.createElement('div'),ctx,{},{})).rejects.toThrow('diag.ppt.invalid-format');});
it('reports the PDF.js dependency before invoking conversion',async()=>{const convertToPdf=vi.fn(async()=>new Uint8Array());await expect(mountPptViewer({fileName:'bad.ppt',data:new Uint8Array([1])},document.createElement('div'),ctx,{convertToPdf},{})).rejects.toThrow('diag.ppt.pdf-missing-dependency');expect(convertToPdf).not.toHaveBeenCalled();});
it('never sends limit-exceeded input to the converter',async()=>{const convertToPdf=vi.fn(async()=>new Uint8Array());await expect(mountPptViewer({fileName:'large.ppt',data:new Uint8Array([1,2])},document.createElement('div'),ctx,{convertToPdf,loadPdfjs:async()=>pdfjs},{limits:{maxInputBytes:1}})).rejects.toThrow('diag.limit-exceeded.input');expect(convertToPdf).not.toHaveBeenCalled();});
it('passes the mount cancellation signal to the converter',async()=>{const abort=new AbortController(),convertToPdf=vi.fn(async(_data:Uint8Array,signal?:AbortSignal)=>{abort.abort();expect(signal).toBe(abort.signal);return new Uint8Array();});await expect(mountPptViewer({fileName:'bad.ppt',data:new Uint8Array([1])},document.createElement('div'),ctx,{convertToPdf,loadPdfjs:async()=>pdfjs},{signal:abort.signal})).rejects.toThrow('mount aborted');});
});
