// @vitest-environment jsdom
import {describe,expect,it} from 'vitest';import type {SlideElement} from '../../parsers/slide-model.js';import {getReadableTextColor,presetGeomToSvgPath,renderSlide,renderSlideElement} from './render.js';import {pptViewerCss} from './styles.js';
const base={x:10,y:20,width:200,height:100,zIndex:3} as const;
describe('PPT element renderer fidelity',()=>{
it('applies image source cropping and flips',()=>{const rendered=renderSlideElement({...base,type:'image',src:'data:image/png;base64,AA==',srcRect:{l:10,t:20,r:30,b:10},flipH:true});const image=rendered.querySelector('img')!;expect(rendered.style.overflow).toBe('hidden');expect(rendered.style.transform).toContain('scaleX(-1)');expect(parseFloat(image.style.width)).toBeCloseTo(166.667,2);expect(parseFloat(image.style.height)).toBeCloseTo(142.857,2);expect(parseFloat(image.style.left)).toBeCloseTo(-16.667,2);expect(parseFloat(image.style.top)).toBeCloseTo(-28.571,2);});
it('renders paragraph and run styles plus text presets',()=>{const rendered=renderSlideElement({...base,type:'text',textStylePreset:'cover-subtitle',fillColor:'#eee',borderColor:'#111',paragraphs:[{text:'Hello',level:2,fontSizePx:30,color:'#123456',bold:true,italic:true,runs:[{text:'Hello',fontSizePx:18,color:'#abcdef',bold:true}]}]});const paragraph=rendered.querySelector('p')!,run=rendered.querySelector('span')!;expect(rendered.dataset.textPreset).toBe('cover-subtitle');expect(paragraph.style.cssText).toContain('font-size: 30px');expect(paragraph.style.color).toBe('rgb(18, 52, 86)');expect(paragraph.style.fontWeight).toBe('700');expect(paragraph.style.marginLeft).toBe('32px');expect(run.style.fontSize).toBe('18px');expect(run.style.color).toBe('rgb(171, 205, 239)');});
it('renders directional lines with arrow markers and flips exactly once',()=>{const rendered=renderSlideElement({...base,type:'shape',presetGeom:'line',flipH:true,flipV:true,headEnd:'oval',tailEnd:'triangle',borderColor:'#ff0000'});const line=rendered.querySelector('line')!;expect(rendered.style.transform).not.toContain('scale');expect(line.getAttribute('x1')).toBe('200');expect(line.getAttribute('y1')).toBe('100');expect(line.getAttribute('x2')).toBe('0');expect(line.getAttribute('marker-start')).toContain('circle-');expect(line.getAttribute('marker-end')).toContain('arrow-');});
it('matches the reference connector marker geometry without clipping',()=>{const rendered=renderSlideElement({...base,type:'shape',presetGeom:'line',headEnd:'oval',tailEnd:'triangle',borderColor:'#404040'});const markers=rendered.querySelectorAll('marker'),arrow=markers[0]!,circle=markers[1]!,svg=rendered.querySelector('svg')!;expect([arrow.getAttribute('markerWidth'),arrow.getAttribute('markerHeight'),arrow.getAttribute('refX'),arrow.getAttribute('refY')]).toEqual(['8','6','8','3']);expect([circle.getAttribute('markerWidth'),circle.getAttribute('markerHeight'),circle.getAttribute('refX'),circle.getAttribute('refY')]).toEqual(['6','6','3','3']);expect(circle.querySelector('circle')?.getAttribute('r')).toBe('2.5');expect(svg.style.overflow).toBe('visible');expect(rendered.style.overflow).toBe('visible');});
it('adds a default arrow marker to bare connector lines but not to decorative endpoints',()=>{const bare=renderSlideElement({...base,type:'shape',presetGeom:'straightConnector1',borderColor:'#000'});expect(bare.querySelector('line')!.getAttribute('marker-end')).toContain('arrow-');const zero=renderSlideElement({...base,width:2,height:2,type:'shape',presetGeom:'line'});expect(zero.querySelector('line')!.getAttribute('marker-end')).toBeNull();});
it('registers a load handler that recolors vector fallback rasters',()=>{const rendered=renderSlideElement({...base,type:'image',src:'data:image/png;base64,AA==',vectorFallback:true});expect(rendered.querySelector('img')).toBeTruthy();});
it('renders chart placeholders with the reference title and subtitle structure',()=>{const placeholder=renderSlideElement({...base,type:'chart',chartKind:'smartart',chartTitle:'Process'});expect(placeholder.querySelector('.omni-ppt__chart-title')?.textContent).toBe('Process');expect(placeholder.querySelector('.omni-ppt__chart-subtitle')?.textContent).toBe('SmartArt placeholder');});
it('keeps the table frame separate from table content',()=>{const rendered=renderSlideElement({...base,type:'table',tableRows:[['A'],['B']]});expect(rendered.classList.contains('omni-ppt__table-frame')).toBe(true);expect(rendered.querySelector(':scope > table.omni-ppt__table')).toBeTruthy();});
it('keeps reference slide, text, table, and chart styling',()=>{expect(pptViewerCss).toContain('.omni-ppt__slide{position:relative;overflow:hidden;border-radius:6px');expect(pptViewerCss).toContain('.omni-ppt__text{padding:2px');expect(pptViewerCss).toContain('.omni-ppt__table-frame{background:#fff;border:1px solid #bdbdbd;overflow:auto}');expect(pptViewerCss).toContain('border:1px solid #d3d3d3;padding:4px 6px');expect(pptViewerCss).toContain('.omni-ppt__chart{display:flex');});
it('prefers custom SVG paths and supports all VS Code preset geometries',()=>{const custom='M 0 0 L 20 20 Z',rendered=renderSlideElement({...base,type:'shape',customSvgPath:custom,fillColor:'#00ff00'});expect(rendered.querySelector('path')?.getAttribute('d')).toBe(custom);for(const preset of ['rightArrow','leftArrow','upArrow','downArrow','roundRect','ellipse','oval','triangle','rect'])expect(presetGeomToSvgPath(preset,200,100),preset).toBeTruthy();});
it('uses slide luminance for text without an explicit color',()=>{expect(getReadableTextColor('#111111')).toBe('#ffffff');expect(getReadableTextColor('#f5f5f5')).toBe('#111111');const rendered=renderSlide({slideNumber:1,widthPx:400,heightPx:300,backgroundColor:'#111111',elements:[{...base,type:'text',paragraphs:[{text:'fallback',level:0},{text:'explicit',level:0,color:'#ff0000'}]}]},1);const lines=rendered.querySelectorAll('p');expect((lines[0] as HTMLElement).style.color).toBe('rgb(255, 255, 255)');expect((lines[1] as HTMLElement).style.color).toBe('rgb(255, 0, 0)');});
it('promotes full-slide negative-z background images without mutating the model',()=>{const background:SlideElement={type:'image',x:0,y:0,width:900,height:600,zIndex:-5,src:'data:image/png;base64,AA=='};const rendered=renderSlide({slideNumber:1,widthPx:1000,heightPx:700,backgroundColor:'#fff',elements:[background]},1);expect((rendered.querySelector('img.omni-ppt__image') as HTMLElement).parentElement?.style.zIndex).toBe('0');expect(background.zIndex).toBe(-5);});
});
